---
name: "build images"

on: [push, pull_request]

jobs:
  docker-build:
    strategy:
      matrix:
        BASE_IMG_TAG: [
          cuda-11.3.1-pytorch-1.12.0-torchvision-0.12.0-torchaudio-0.11.0-ubuntu-20.04,
          cuda-11.3.1-pytorch-1.11.0-torchvision-0.12.0-torchaudio-0.11.0-ubuntu-20.04,
          cuda-11.6.1-pytorch-1.12.0-torchvision-0.12.0-torchaudio-0.11.0-ubuntu-20.04,
          cuda-11.6.1-pytorch-1.11.0-torchvision-0.12.0-torchaudio-0.11.0-ubuntu-20.04
          ]

    runs-on: ubuntu-latest

    steps:
      - name: Set ON_MAIN_FORK_AND_BRANCH
        run: echo "ON_MAIN_FORK_AND_BRANCH=$([ "$GITHUB_REPOSITORY" == "walkerlab/pytorch-docker" ] && [ "$GITHUB_REF_NAME" == "main" ] &&  echo true || echo true)" >> $GITHUB_ENV  # If it is from the main fork and is main branch

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      
      - name: Login to DockerHub
        if: env.ON_MAIN_FORK_AND_BRANCH == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            BASE_IMG_NAME=walkerlab/pytorch:${{ matrix.BASE_IMG_TAG }}
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ env.ON_MAIN_FORK_AND_BRANCH == 'true' }}
          tags: walkerlab/pytorch-jupyter:${{ matrix.BASE_IMG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}